function radio1() {
radioList.innerHTML = '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1421411980&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/arboricum-sandorsi" title="Arboricum Sandorsi" target="_blank" style="color: #cccccc; text-decoration: none;">Arboricum Sandorsi</a> · <a href="https://soundcloud.com/arboricum-sandorsi/sets/relaxing-music-for-stress-1" title="Relaxing music for stress relief Vol.3" target="_blank" style="color: #cccccc; text-decoration: none;">Relaxing music for stress relief Vol.3</a></div>';
}

function radio2() {
radioList.innerHTML = '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1414354141&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/arboricum-sandorsi" title="Arboricum Sandorsi" target="_blank" style="color: #cccccc; text-decoration: none;">Arboricum Sandorsi</a> · <a href="https://soundcloud.com/arboricum-sandorsi/sets/relaxing-music-vol-2" title="Relaxing music for stress relief Vol.2" target="_blank" style="color: #cccccc; text-decoration: none;">Relaxing music for stress relief Vol.2</a></div>';
}

function radio3() {
radioList.innerHTML = '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1408698568&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/arboricum-sandorsi" title="Arboricum Sandorsi" target="_blank" style="color: #cccccc; text-decoration: none;">Arboricum Sandorsi</a> · <a href="https://soundcloud.com/arboricum-sandorsi/sets/relaxing-music-for-stress-relief-vol1" title="Relaxing music for stress relief Vol.1" target="_blank" style="color: #cccccc; text-decoration: none;">Relaxing music for stress relief Vol.1</a></div>';
}

function radio4() {
radioList.innerHTML = '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1412338756&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/arboricum-sandorsi" title="Arboricum Sandorsi" target="_blank" style="color: #cccccc; text-decoration: none;">Arboricum Sandorsi</a> · <a href="https://soundcloud.com/arboricum-sandorsi/sets/3-voices-symphonies-transcribed-for-synth" title="Invenzioni a 3 voci di J.S.Bach trascritte per synth" target="_blank" style="color: #cccccc; text-decoration: none;">Invenzioni a 3 voci di J.S.Bach trascritte per synth</a></div>';	
}

function radio5() {
radioList.innerHTML	= '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1363480504&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/arboricum-sandorsi" title="Arboricum Sandorsi" target="_blank" style="color: #cccccc; text-decoration: none;">Arboricum Sandorsi</a> · <a href="https://soundcloud.com/arboricum-sandorsi/sets/electronic-tangos" title="Electronic tangos" target="_blank" style="color: #cccccc; text-decoration: none;">Electronic tangos</a></div>';
}

function radio6() {
radioList.innerHTML = '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1363262752&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/arboricum-sandorsi" title="Arboricum Sandorsi" target="_blank" style="color: #cccccc; text-decoration: none;">Arboricum Sandorsi</a> · <a href="https://soundcloud.com/arboricum-sandorsi/sets/mournful-music" title="Mournful time" target="_blank" style="color: #cccccc; text-decoration: none;">Mournful time</a></div>';
}

function radio7() {
radioList.innerHTML = '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1362915076&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/arboricum-sandorsi" title="Arboricum Sandorsi" target="_blank" style="color: #cccccc; text-decoration: none;">Arboricum Sandorsi</a> · <a href="https://soundcloud.com/arboricum-sandorsi/sets/meditation-music" title="Meditation music" target="_blank" style="color: #cccccc; text-decoration: none;">Meditation music</a></div>';
}

function radio8() {
radioList.innerHTML = '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1291719421&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/arboricum-sandorsi" title="Arboricum Sandorsi" target="_blank" style="color: #cccccc; text-decoration: none;">Arboricum Sandorsi</a> · <a href="https://soundcloud.com/arboricum-sandorsi/sets/dancing-with-my-soul" title="Dancing with my soul" target="_blank" style="color: #cccccc; text-decoration: none;">Dancing with my soul</a></div>';
}

function radio9() {
radioList.innerHTML = '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1363130572&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/arboricum-sandorsi" title="Arboricum Sandorsi" target="_blank" style="color: #cccccc; text-decoration: none;">Arboricum Sandorsi</a> · <a href="https://soundcloud.com/arboricum-sandorsi/sets/parallel-universes" title="Parallel universes" target="_blank" style="color: #cccccc; text-decoration: none;">Parallel universes</a></div>';
}

function radio10() {
radioList.innerHTML = '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1362368398&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/arboricum-sandorsi" title="Arboricum Sandorsi" target="_blank" style="color: #cccccc; text-decoration: none;">Arboricum Sandorsi</a> · <a href="https://soundcloud.com/arboricum-sandorsi/sets/music-fragments-from-parallel-worlds" title="Music fragments from parallel worlds" target="_blank" style="color: #cccccc; text-decoration: none;">Music fragments from parallel worlds</a></div>';
}

function radio11() {
radioList.innerHTML = '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1362655453&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/arboricum-sandorsi" title="Arboricum Sandorsi" target="_blank" style="color: #cccccc; text-decoration: none;">Arboricum Sandorsi</a> · <a href="https://soundcloud.com/arboricum-sandorsi/sets/singles" title="Singles" target="_blank" style="color: #cccccc; text-decoration: none;">Singles</a></div>';
}